//定义静态变量
export const SET_MAP_CLICK_LISTENER = 'SET_MAP_CLICK_LISTENER';
export const SET_IO_RECEIVER_LISTENER = 'SET_IO_RECEIVER_LISTENER';
export const SET_MAP_CLICK_POLYLINE = 'SET_MAP_CLICK_POLYLINE';
export const SET_IO_QUERY_DB = 'SET_IO_QUERY_DB';
export const SET_ADHOC_RECEIVER_LISTENER = 'SET_ADHOC_RECEIVER_LISTENER';
export const SET_MAP_TAP_LISTENER = 'SET_MAP_TAP_LISTENER';
